title: Lexsift Manual
description: Documentation of Lexsift features and usage
theme: just-the-docs

url: https://michaeldolzani.github.io

aux_links:
  Lexsift homepage: https://github.com/MichaelDolzani/Lexsift

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
